POST http://localhost:5005/cat/list
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjI0YzM0MjlhNzAzODQzMjg2YjBmM2UiLCJpYXQiOjE1OTYzODEzNjJ9.BIRWPGNV10VfzC02M1Nt3SNZNax3WtWWPX_UsRqK6Qo

{
    "limit": 10,
    "page": 1,
    "sort": "-cat",
    "when" : {
        "deleted" : false
    }
}

######

PUT http://localhost:5005/cat/4
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjI0YzM0MjlhNzAzODQzMjg2YjBmM2UiLCJpYXQiOjE1OTYzODEzNjJ9.BIRWPGNV10VfzC02M1Nt3SNZNax3WtWWPX_UsRqK6Qo

{
    "cat": "HEHE"
}

######

GET http://localhost:5005/cat/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjI0YzM0MjlhNzAzODQzMjg2YjBmM2UiLCJpYXQiOjE1OTYzODEzNjJ9.BIRWPGNV10VfzC02M1Nt3SNZNax3WtWWPX_UsRqK6Qo

#######

DELETE http://localhost:5005/cat/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjI0YzM0MjlhNzAzODQzMjg2YjBmM2UiLCJpYXQiOjE1OTYzODEzNjJ9.BIRWPGNV10VfzC02M1Nt3SNZNax3WtWWPX_UsRqK6Qo

[1,2]

#######

